Repository MaRDI4NFDI/docker-importer, pull requests merged in 2022-05, with the labels that each got.

#14 restructure to create python module namespace
  scripts/import.py
  setup.py
  src/mardi_importer/__init__.py
  src/mardi_importer/importer/Importer.py
  src/mardi_importer/importer/__init__.py
  src/mardi_importer/wikidata/EntityCreator.py
  src/mardi_importer/wikidata/__init__.py
  src/mardi_importer/zbmath/ZBMathSource.py
  src/mardi_importer/zbmath/__init__.py
  src/mardi_importer/zbmath/misc.py
Labels: enhancement

#16 remove import.py from setup script
  setup.py
Labels: enhancement

#17 document functions with sphinx
  src/mardi_importer/importer/Importer.py
  src/mardi_importer/wikidata/EntityCreator.py
  src/mardi_importer/zbmath/ZBMathSource.py
  src/mardi_importer/zbmath/misc.py
Labels: documentation

#23 Fix editable pip install inside docker container
  Dockerfile
Labels: bug

#30 fix memory bug
  mediawiki/LocalSettings.d/LocalSettings.override.php
Labels: bug

#31 add script to get wikidata labels and remove unnecessary spaces from …
  src/mardi_importer/scripts/get_wikidata_labels.py
Labels: enhancement
